In [323]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import MinMaxScaler

In [324]:
df= pd.read_csv('train.csv')

In [325]:
df.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [326]:
df.drop(columns=['PassengerId','Name'],inplace=True)
df.drop(columns=['Ticket'],inplace=True)

In [327]:
df.drop(columns=['Cabin'],inplace=True)

In [328]:
df.sample(5)

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
649         1       3  female  23.0      0      0   7.5500        S
39          1       3  female  14.0      1      0  11.2417        C
513         1       1  female  54.0      1      0  59.4000        C
369         1       1  female  24.0      0      0  69.3000        C
75          0       3    male  25.0      0      0   7.6500        S

In [329]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.drop(['Survived'],axis=1),df['Survived'],test_size=0.2,random_state=42)


In [330]:
x_train.shape,y_train.shape

((712, 7), (712,))

In [331]:
y_test.shape,x_test.shape

((179,), (179, 7))

In [332]:
from sklearn.compose import ColumnTransformer

In [333]:
x_train.columns

Index(['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked'], dtype='object')

In [334]:

level1 =ColumnTransformer([
    ('age',SimpleImputer(),[2]),
    ('Embarked',SimpleImputer(strategy='most_frequent'),[6])
    
    
    
    ],remainder='passthrough')

In [335]:
level1.fit_transform(x_test)

array([[30.505845070422534, 'C', 3, ..., 1, 1, 15.2458],
       [31.0, 'S', 2, ..., 0, 0, 10.5],
       [20.0, 'S', 3, ..., 0, 0, 7.925],
       ...,
       [38.0, 'S', 3, ..., 1, 5, 31.3875],
       [17.0, 'S', 2, ..., 0, 0, 10.5],
       [4.0, 'S', 3, ..., 1, 1, 16.7]], shape=(179, 7), dtype=object)

In [336]:
x_train

Pclass     Sex   Age  SibSp  Parch      Fare Embarked
331       1    male  45.5      0      0   28.5000        S
733       2    male  23.0      0      0   13.0000        S
382       3    male  32.0      0      0    7.9250        S
704       3    male  26.0      1      0    7.8542        S
813       3  female   6.0      4      2   31.2750        S
..      ...     ...   ...    ...    ...       ...      ...
106       3  female  21.0      0      0    7.6500        S
270       1    male   NaN      0      0   31.0000        S
860       3    male  41.0      2      0   14.1083        S
435       1  female  14.0      1      2  120.0000        S
102       1    male  21.0      0      1   77.2875        S

[712 rows x 7 columns]

#### one hot encoding

In [337]:
level2 = ColumnTransformer(
    [
    
    ('one_hot_encode',OneHotEncoder(sparse_output=False,handle_unknown='ignore',dtype='int32'),[1,6])
    
]  ,remainder='passthrough')

In [338]:
level2

ColumnTransformer(remainder='passthrough',
                  transformers=[('one_hot_encode',
                                 OneHotEncoder(dtype='int32',
                                               handle_unknown='ignore',
                                               sparse_output=False),
                                 [1, 6])])

In [339]:
level2.fit_transform(x_train)

array([[  0.    ,   1.    ,   0.    , ...,   0.    ,   0.    ,  28.5   ],
       [  0.    ,   1.    ,   0.    , ...,   0.    ,   0.    ,  13.    ],
       [  0.    ,   1.    ,   0.    , ...,   0.    ,   0.    ,   7.925 ],
       ...,
       [  0.    ,   1.    ,   0.    , ...,   2.    ,   0.    ,  14.1083],
       [  1.    ,   0.    ,   0.    , ...,   1.    ,   2.    , 120.    ],
       [  0.    ,   1.    ,   0.    , ...,   0.    ,   1.    ,  77.2875]],
      shape=(712, 11))

In [340]:
level2.fit_transform(x_train)

array([[  0.    ,   1.    ,   0.    , ...,   0.    ,   0.    ,  28.5   ],
       [  0.    ,   1.    ,   0.    , ...,   0.    ,   0.    ,  13.    ],
       [  0.    ,   1.    ,   0.    , ...,   0.    ,   0.    ,   7.925 ],
       ...,
       [  0.    ,   1.    ,   0.    , ...,   2.    ,   0.    ,  14.1083],
       [  1.    ,   0.    ,   0.    , ...,   1.    ,   2.    , 120.    ],
       [  0.    ,   1.    ,   0.    , ...,   0.    ,   1.    ,  77.2875]],
      shape=(712, 11))

In [341]:
level3 =ColumnTransformer([
    ('scale',MinMaxScaler(),slice(0,10))
])

In [342]:
#feature scaling

from sklearn.feature_selection import SelectKBest

In [343]:
level4= SelectKBest(score_func=chi2,k=9)

In [344]:
from sklearn.tree import DecisionTreeClassifier

In [345]:
level5 = DecisionTreeClassifier()

In [346]:
from sklearn.pipeline import Pipeline

pipe = Pipeline([
    ('level1',level1),
    ('level2',level2),
    ('level3',level3),
    ('level4',level4),
    ('level5',level5)
    
    
])

In [347]:
# 
from sklearn.pipeline import make_pipeline
pipe2 = make_pipeline(level1,level2,level3,level4,level5)

In [356]:
pipe2.fit(x_train,y_train)

Pipeline(steps=[('columntransformer-1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('age', SimpleImputer(), [2]),
                                                 ('Embarked',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  [6])])),
                ('columntransformer-2',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('one_hot_encode',
                                                  OneHotEncoder(dtype='int32',
                                                                handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [1, 6])])),
                ('columntransformer-3',
                 ColumnTransformer(transformers=[('scale', MinMaxScaler(),
                                                  slice(0, 10, None))])),
                ('selectkbest',
                 SelectKBest(k=9,
                             score_func=<function chi2 at 0x0000019063318FE0>)),
                ('decisiontreeclassifier', DecisionTreeClassifier())])

In [362]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('level1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('age', SimpleImputer(), [2]),
                                                 ('Embarked',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  [6])])),
                ('level2',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('one_hot_encode',
                                                  OneHotEncoder(dtype='int32',
                                                                handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [1, 6])])),
                ('level3',
                 ColumnTransformer(transformers=[('scale', MinMaxScaler(),
                                                  slice(0, 10, None))])),
                ('level4',
                 SelectKBest(k=9,
                             score_func=<function chi2 at 0x0000019063318FE0>)),
                ('level5', DecisionTreeClassifier())])

In [367]:

#! y pred
y_pred = pipe.predict(x_test) 

In [368]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6256983240223464

#### cross validation

In [ ]:
from sklearn.model_selection import cross_val_score
cross_val_score(pipe,x_train,y_train,cv=5,scoring='accuracy').mean(     )

np.float64(0.6391214419383433)

#### grid search using pipline

In [ ]:
param ={
    
    
    "level5__max_depth":[1,2,3,4,5,None]
}

In [380]:

from sklearn.model_selection import GridSearchCV
grid =GridSearchCV(pipe,param,cv=5,scoring='accuracy')
grid.fit(x_train,y_train)

# from sklearn.model_selection import GridSearchCV

# grid = GridSearchCV(pipe, param, cv=5, scoring='accuracy')
# grid.fit(x_train, y_train)


GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('level1',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('age',
                                                                         SimpleImputer(),
                                                                         [2]),
                                                                        ('Embarked',
                                                                         SimpleImputer(strategy='most_frequent'),
                                                                         [6])])),
                                       ('level2',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('one_hot_encode',
                                                                         OneHotEncoder(dtype='int32',
                                                                                       handle_unknown='ignore',
                                                                                       sparse_output=False),
                                                                         [1,
                                                                          6])])),
                                       ('level3',
                                        ColumnTransformer(transformers=[('scale',
                                                                         MinMaxScaler(),
                                                                         slice(0, 10, None))])),
                                       ('level4',
                                        SelectKBest(k=9,
                                                    score_func=<function chi2 at 0x0000019063318FE0>)),
                                       ('level5', DecisionTreeClassifier())]),
             param_grid={}, scoring='accuracy')



#### another way to do this thing

In [348]:

numerical= Pipeline([
    ('one',SimpleImputer()),
    ('two',SimpleImputer(strategy='most_frequent'))
])



In [349]:
category = Pipeline([
    ('one',OneHotEncoder(sparse_output=False,handle_unknown='ignore',dtype='int32'))
])

In [350]:
process =ColumnTransformer([
    
    ('num',numerical),
    ('cat',category)
])

In [351]:
Pipeline=Pipeline([
    ('pr',process),
    ('model',DecisionTreeClassifier())
])

In [ ]:
x_train,x_test